# Pour tout push dans le repo
# - déclencher le build d'une nouvelle image docker en utilisant le Dockerfile
# - et faire un push vers dockerHub .

name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub ACtions
on: [push]
jobs : 
  check-bats-version:
    runs-on: unbuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: corefr
          password: Azerty123
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: corefr/getting-started:latest
